add_newline = false
format = """
$time $username@${custom.hostname}$directory\
$git_branch$git_status\
$line_break$character
"""
right_format = """
$cmd_duration
"""

[character]
success_symbol = "[➜](green)"
error_symbol = "[➜](red)"

[cmd_duration]
min_time = 1000
show_milliseconds = false
format = '[$duration]($style) '
style = 'fg:#fda400'

[directory]
truncation_length = 2
truncation_symbol = "…/"
style = 'blue'

[git_branch]
format = '\[[$branch]($style)'
style = 'bright-white'

[git_status]
format = '([$all_status$ahead_behind\]]($style)) '
ahead = "[↑](cyan)"
behind = "[↓](red)"
conflicted = '[✖](fg:red bg:#2B2129)'
deleted = '[✖](purple)'
modified = '[●](red)'
staged = '[●](green)'
stashed = '[⚑](yellow)'
untracked = '[●](blue)'
up_to_date = "[✔](green)"
style = 'bright-white'

[line_break]
disabled = true

[package]
disabled = true

[time]
disabled = false
format = '[$time]($style)'
time_format = "%T"
style = 'bright-black'

[username]
show_always = false
style_user = 'fg:#5AB6D3 bg:#1E2B37'
style_root = 'fg:#C85550 bg:#2B2129'
format = '[$user]($style)'

[custom.hostname]
format = '[host]'
when = 'true'
