add_newline = false
format = """
$os$time $username@${custom.hostname}$directory\
$git_branch$git_status\
$line_break$character
"""
right_format = """$cmd_duration"""

[os]
format = '[$symbol](bold white) '   
disabled = false

[os.symbols]
Linux = "[󰌽](bold fg:#efc04b)"
Ubuntu = "[󰕈](bold fg:#d55e33)"
Windows = "[](bold fg:#50a4ea)"
Macos = '[󰀵](bold white)'

[character]
success_symbol = "[➜](green)"
error_symbol = "[➜](red)"

[cmd_duration]
min_time = 1000
show_milliseconds = false
format = '[ $duration]($style) '
style = 'bright-black'

[directory]
truncation_length = 2
truncation_symbol = "…/"
read_only = '[](yellow)'
style = 'blue'

[git_branch]
symbol = '[](fg:bright-black)'
format = '\[[$branch]($style)'
style = 'bright-white'

[git_status]
format = '([$all_status$ahead_behind\]]($style)) '
ahead = "[↑](cyan)"
behind = "[↓](red)"
conflicted = '[✖](fg:red bg:#2B2129)'
deleted = '[✖](purple)'
modified = '[●](red)'
staged = '[●](green)'
stashed = '[⚑](yellow)'
untracked = '[●](blue)'
up_to_date = "[✔](green)"
style = 'bright-white'

[line_break]
disabled = true

[package]
disabled = true

[time]
disabled = false
format = '[$time]($style)'
time_format = "%T"
style = 'bright-black'

[username]
show_always = false
style_user = 'fg:#5AB6D3 bg:#1E2B37'
style_root = 'fg:#C85550 bg:#2B2129'
format = '[$user]($style)'

[custom.hostname]
format = '[imac](bright-green)'
when = 'true'
